name: auth
description: 'A new Flutter project.'

publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository
  firebase_auth: ^4.17.8
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
