// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_VJidejuvV0e54W-4OWXanXJSlZdOqVg',
    appId: '1:179334251320:web:5cbd7d8bbb578e3987b7cd',
    messagingSenderId: '179334251320',
    projectId: 'example-auth-aaee1',
    authDomain: 'example-auth-aaee1.firebaseapp.com',
    storageBucket: 'example-auth-aaee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqPEgrLhjOSMhbk1BRcm-ZG-SKJDZZWcU',
    appId: '1:179334251320:android:aef37df1bea5a65c87b7cd',
    messagingSenderId: '179334251320',
    projectId: 'example-auth-aaee1',
    storageBucket: 'example-auth-aaee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDalKXJYFYOjNjnWbPImnNSG_YqHdrdiiE',
    appId: '1:179334251320:ios:be1e3a1a7041886087b7cd',
    messagingSenderId: '179334251320',
    projectId: 'example-auth-aaee1',
    storageBucket: 'example-auth-aaee1.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDalKXJYFYOjNjnWbPImnNSG_YqHdrdiiE',
    appId: '1:179334251320:ios:891bb43847524d5487b7cd',
    messagingSenderId: '179334251320',
    projectId: 'example-auth-aaee1',
    storageBucket: 'example-auth-aaee1.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
